# Generated by Django 4.2 on 2023-07-17 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_article_dislike_article_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
