# Generated by Django 4.2 on 2023-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like',
        ),
    ]
